WIP, need to investigate a failure in conda-build
  File "/home/rdonnelly/conda/conda-build/conda_build/metadata.py", line 211, in _trim_None_strings
    for key, value in meta_dict.items():
AttributeError: 'str' object has no attribute 'items'